version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    init: true

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    init: true
    depends_on:
      - api
    ports:
      - 8000:80

  env:
    build:
      context: .
      dockerfile: Dockerfile-env
    init: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/code
    ports:
      - 3000:3000
      - 5000:5000

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-20210311
    environment:
      - SCREEN_WIDTH=960
      - SCREEN_HEIGHT=1280
      - SCREEN_DEPTH=24
    ports:
      - 5900:5900
